# syntax=docker/dockerfile:1
FROM node:20-alpine

WORKDIR /app

COPY package.json openapi-ts.config.ts .prettierrc.json ./
COPY *.yaml ./

# Install dependencies with latest versions
RUN npm i @hey-api/client-axios axios && \
    npm i -D @hey-api/openapi-ts prettier

# Generate the OpenAPI client
RUN npm run generate-openapi-client

# Publish to npm registry
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc \
    npm publish