// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	APIKeyScopes = "APIKey.Scopes"
)

// BranchName defines model for BranchName.
type BranchName = string

// CreateServiceRequest defines model for CreateServiceRequest.
type CreateServiceRequest struct {
	Service ServiceInput `json:"service"`
}

// CreateServiceResponse defines model for CreateServiceResponse.
type CreateServiceResponse struct {
	Service Service `json:"service"`
}

// DockerComposePath Path to docker-compose file in service
type DockerComposePath = string

// DockerfilePath Path to Dockerfile file in service
type DockerfilePath = string

// EnvPath Path to .env file in service
type EnvPath = string

// EnvVars defines model for EnvVars.
type EnvVars = map[string]interface{}

// GetServiceResponse defines model for GetServiceResponse.
type GetServiceResponse struct {
	Service Service `json:"service"`
}

// GitConfiguration defines model for GitConfiguration.
type GitConfiguration struct {
	union json.RawMessage
}

// GitConfigurationOptions defines model for GitConfigurationOptions.
type GitConfigurationOptions struct {
	BranchName BranchName `json:"branchName"`
	SshUrl     SSHUrl     `json:"sshUrl"`
}

// ID Resource ID - ULID
type ID = string

// ListServicesResponse defines model for ListServicesResponse.
type ListServicesResponse struct {
	// NextToken Pagination token
	NextToken *NextToken `json:"nextToken,omitempty"`
	Services  Services   `json:"services"`
}

// NPMConfiguration defines model for NPMConfiguration.
type NPMConfiguration struct {
	Npm NPMConfigurationChoices `json:"npm"`
}

// NPMConfigurationChoices defines model for NPMConfigurationChoices.
type NPMConfigurationChoices struct {
	union json.RawMessage
}

// NPMLibrary defines model for NPMLibrary.
type NPMLibrary struct {
	Library NPMLibraryConfiguration `json:"library"`
}

// NPMLibraryConfiguration defines model for NPMLibraryConfiguration.
type NPMLibraryConfiguration = map[string]interface{}

// NPMService defines model for NPMService.
type NPMService struct {
	Service NPMServiceConfiguration `json:"service"`
}

// NPMServiceConfiguration defines model for NPMServiceConfiguration.
type NPMServiceConfiguration struct {
	// DockerComposePath Path to docker-compose file in service
	DockerComposePath DockerComposePath `json:"dockerComposePath"`

	// DockerfilePath Path to Dockerfile file in service
	DockerfilePath DockerfilePath `json:"dockerfilePath"`

	// EnvPath Path to .env file in service
	EnvPath EnvPath `json:"envPath"`
	EnvVars EnvVars `json:"envVars"`
}

// Name Service Name
type Name = string

// NextToken Pagination token
type NextToken = string

// OpenAPIConfiguration defines model for OpenAPIConfiguration.
type OpenAPIConfiguration struct {
	Openapi OpenAPIConfigurationChoices `json:"openapi"`
}

// OpenAPIConfigurationChoices defines model for OpenAPIConfigurationChoices.
type OpenAPIConfigurationChoices struct {
	GoClient         *OpenAPIGoClientConfig         `json:"goClient,omitempty"`
	TypescriptClient *OpenAPITypescriptClientConfig `json:"typescriptClient,omitempty"`

	// YamlFile Absolute path to openapi definition in yaml format
	YamlFile string `json:"yamlFile"`
}

// OpenAPIGoClientConfig defines model for OpenAPIGoClientConfig.
type OpenAPIGoClientConfig struct {
	// Name Name of go client.
	Name string `json:"name"`
}

// OpenAPITypescriptClientConfig defines model for OpenAPITypescriptClientConfig.
type OpenAPITypescriptClientConfig struct {
	// Name Name of Typescript client. Service defined scope will be added.
	Name string `json:"name"`
}

// SSHUrl defines model for SSHUrl.
type SSHUrl = string

// Service defines model for Service.
type Service struct {
	Configuration ServiceConfiguration `json:"configuration"`
	Git           GitConfiguration     `json:"git"`

	// Id Resource ID - ULID
	Id ID `json:"id"`

	// Name Service Name
	Name Name `json:"name"`
}

// ServiceConfiguration defines model for ServiceConfiguration.
type ServiceConfiguration struct {
	union json.RawMessage
}

// ServiceInput defines model for ServiceInput.
type ServiceInput struct {
	Configuration ServiceConfiguration `json:"configuration"`
	Git           GitConfiguration     `json:"git"`

	// Name Service Name
	Name Name `json:"name"`
}

// Services defines model for Services.
type Services = []Service

// MaxResults defines model for MaxResults.
type MaxResults = int

// NextTokenInput defines model for NextTokenInput.
type NextTokenInput = string

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Message *string `json:"message,omitempty"`
}

// Conflict defines model for Conflict.
type Conflict struct {
	Message *string `json:"message,omitempty"`
}

// Forbidden defines model for Forbidden.
type Forbidden struct {
	Message *string `json:"message,omitempty"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	Message *string `json:"message,omitempty"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Message *string `json:"message,omitempty"`
}

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests struct {
	Message *string `json:"message,omitempty"`
}

// UnAuthorized defines model for UnAuthorized.
type UnAuthorized struct {
	Message *string `json:"message,omitempty"`
}

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	// MaxResults Max number of results to return when paginating
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// NextToken Pagination token
	NextToken *NextTokenInput `form:"next_token,omitempty" json:"next_token,omitempty"`
}

// CreateServiceJSONRequestBody defines body for CreateService for application/json ContentType.
type CreateServiceJSONRequestBody = CreateServiceRequest

// AsGitConfigurationOptions returns the union data inside the GitConfiguration as a GitConfigurationOptions
func (t GitConfiguration) AsGitConfigurationOptions() (GitConfigurationOptions, error) {
	var body GitConfigurationOptions
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGitConfigurationOptions overwrites any union data inside the GitConfiguration as the provided GitConfigurationOptions
func (t *GitConfiguration) FromGitConfigurationOptions(v GitConfigurationOptions) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGitConfigurationOptions performs a merge with any union data inside the GitConfiguration, using the provided GitConfigurationOptions
func (t *GitConfiguration) MergeGitConfigurationOptions(v GitConfigurationOptions) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t GitConfiguration) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GitConfiguration) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsNPMService returns the union data inside the NPMConfigurationChoices as a NPMService
func (t NPMConfigurationChoices) AsNPMService() (NPMService, error) {
	var body NPMService
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNPMService overwrites any union data inside the NPMConfigurationChoices as the provided NPMService
func (t *NPMConfigurationChoices) FromNPMService(v NPMService) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNPMService performs a merge with any union data inside the NPMConfigurationChoices, using the provided NPMService
func (t *NPMConfigurationChoices) MergeNPMService(v NPMService) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNPMLibrary returns the union data inside the NPMConfigurationChoices as a NPMLibrary
func (t NPMConfigurationChoices) AsNPMLibrary() (NPMLibrary, error) {
	var body NPMLibrary
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNPMLibrary overwrites any union data inside the NPMConfigurationChoices as the provided NPMLibrary
func (t *NPMConfigurationChoices) FromNPMLibrary(v NPMLibrary) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNPMLibrary performs a merge with any union data inside the NPMConfigurationChoices, using the provided NPMLibrary
func (t *NPMConfigurationChoices) MergeNPMLibrary(v NPMLibrary) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NPMConfigurationChoices) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NPMConfigurationChoices) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsNPMConfiguration returns the union data inside the ServiceConfiguration as a NPMConfiguration
func (t ServiceConfiguration) AsNPMConfiguration() (NPMConfiguration, error) {
	var body NPMConfiguration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNPMConfiguration overwrites any union data inside the ServiceConfiguration as the provided NPMConfiguration
func (t *ServiceConfiguration) FromNPMConfiguration(v NPMConfiguration) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNPMConfiguration performs a merge with any union data inside the ServiceConfiguration, using the provided NPMConfiguration
func (t *ServiceConfiguration) MergeNPMConfiguration(v NPMConfiguration) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOpenAPIConfiguration returns the union data inside the ServiceConfiguration as a OpenAPIConfiguration
func (t ServiceConfiguration) AsOpenAPIConfiguration() (OpenAPIConfiguration, error) {
	var body OpenAPIConfiguration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOpenAPIConfiguration overwrites any union data inside the ServiceConfiguration as the provided OpenAPIConfiguration
func (t *ServiceConfiguration) FromOpenAPIConfiguration(v OpenAPIConfiguration) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOpenAPIConfiguration performs a merge with any union data inside the ServiceConfiguration, using the provided OpenAPIConfiguration
func (t *ServiceConfiguration) MergeOpenAPIConfiguration(v OpenAPIConfiguration) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ServiceConfiguration) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ServiceConfiguration) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListServices request
	ListServices(ctx context.Context, params *ListServicesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateServiceWithBody request with any body
	CreateServiceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateService(ctx context.Context, body CreateServiceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetService request
	GetService(ctx context.Context, name Name, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListServices(ctx context.Context, params *ListServicesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListServicesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateServiceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateServiceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateService(ctx context.Context, body CreateServiceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateServiceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetService(ctx context.Context, name Name, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetServiceRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListServicesRequest generates requests for ListServices
func NewListServicesRequest(server string, params *ListServicesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.MaxResults != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "max_results", runtime.ParamLocationQuery, *params.MaxResults); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NextToken != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "next_token", runtime.ParamLocationQuery, *params.NextToken); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateServiceRequest calls the generic CreateService builder with application/json body
func NewCreateServiceRequest(server string, body CreateServiceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateServiceRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateServiceRequestWithBody generates requests for CreateService with any type of body
func NewCreateServiceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetServiceRequest generates requests for GetService
func NewGetServiceRequest(server string, name Name) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "name", runtime.ParamLocationPath, name)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListServicesWithResponse request
	ListServicesWithResponse(ctx context.Context, params *ListServicesParams, reqEditors ...RequestEditorFn) (*ListServicesResp, error)

	// CreateServiceWithBodyWithResponse request with any body
	CreateServiceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateServiceResp, error)

	CreateServiceWithResponse(ctx context.Context, body CreateServiceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateServiceResp, error)

	// GetServiceWithResponse request
	GetServiceWithResponse(ctx context.Context, name Name, reqEditors ...RequestEditorFn) (*GetServiceResp, error)
}

type ListServicesResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListServicesResponse
	JSON400      *BadRequest
	JSON401      *UnAuthorized
	JSON403      *Forbidden
	JSON429      *TooManyRequests
	JSON5XX      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r ListServicesResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListServicesResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateServiceResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateServiceResponse
	JSON400      *BadRequest
	JSON401      *UnAuthorized
	JSON403      *Forbidden
	JSON409      *Conflict
	JSON429      *TooManyRequests
	JSON5XX      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r CreateServiceResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateServiceResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetServiceResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetServiceResponse
	JSON401      *UnAuthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON429      *TooManyRequests
	JSON5XX      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetServiceResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetServiceResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListServicesWithResponse request returning *ListServicesResp
func (c *ClientWithResponses) ListServicesWithResponse(ctx context.Context, params *ListServicesParams, reqEditors ...RequestEditorFn) (*ListServicesResp, error) {
	rsp, err := c.ListServices(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListServicesResp(rsp)
}

// CreateServiceWithBodyWithResponse request with arbitrary body returning *CreateServiceResp
func (c *ClientWithResponses) CreateServiceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateServiceResp, error) {
	rsp, err := c.CreateServiceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateServiceResp(rsp)
}

func (c *ClientWithResponses) CreateServiceWithResponse(ctx context.Context, body CreateServiceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateServiceResp, error) {
	rsp, err := c.CreateService(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateServiceResp(rsp)
}

// GetServiceWithResponse request returning *GetServiceResp
func (c *ClientWithResponses) GetServiceWithResponse(ctx context.Context, name Name, reqEditors ...RequestEditorFn) (*GetServiceResp, error) {
	rsp, err := c.GetService(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetServiceResp(rsp)
}

// ParseListServicesResp parses an HTTP response from a ListServicesWithResponse call
func ParseListServicesResp(rsp *http.Response) (*ListServicesResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListServicesResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListServicesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnAuthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseCreateServiceResp parses an HTTP response from a CreateServiceWithResponse call
func ParseCreateServiceResp(rsp *http.Response) (*CreateServiceResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateServiceResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateServiceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnAuthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetServiceResp parses an HTTP response from a GetServiceWithResponse call
func ParseGetServiceResp(rsp *http.Response) (*GetServiceResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetServiceResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetServiceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnAuthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /services)
	ListServices(c *gin.Context, params ListServicesParams)

	// (POST /services)
	CreateService(c *gin.Context)

	// (GET /services/{name})
	GetService(c *gin.Context, name Name)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListServices operation middleware
func (siw *ServerInterfaceWrapper) ListServices(c *gin.Context) {

	var err error

	c.Set(APIKeyScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServicesParams

	// ------------- Optional query parameter "max_results" -------------

	err = runtime.BindQueryParameter("form", true, false, "max_results", c.Request.URL.Query(), &params.MaxResults)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter max_results: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "next_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "next_token", c.Request.URL.Query(), &params.NextToken)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter next_token: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListServices(c, params)
}

// CreateService operation middleware
func (siw *ServerInterfaceWrapper) CreateService(c *gin.Context) {

	c.Set(APIKeyScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateService(c)
}

// GetService operation middleware
func (siw *ServerInterfaceWrapper) GetService(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(APIKeyScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetService(c, name)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/services", wrapper.ListServices)
	router.POST(options.BaseURL+"/services", wrapper.CreateService)
	router.GET(options.BaseURL+"/services/:name", wrapper.GetService)
}

type BadRequestJSONResponse struct {
	Message *string `json:"message,omitempty"`
}

type ConflictJSONResponse struct {
	Message *string `json:"message,omitempty"`
}

type ForbiddenJSONResponse struct {
	Message *string `json:"message,omitempty"`
}

type InternalServerErrorJSONResponse struct {
	Message *string `json:"message,omitempty"`
}

type NotFoundJSONResponse struct {
	Message *string `json:"message,omitempty"`
}

type TooManyRequestsJSONResponse struct {
	Message *string `json:"message,omitempty"`
}

type UnAuthorizedJSONResponse struct {
	Message *string `json:"message,omitempty"`
}

type ListServicesRequestObject struct {
	Params ListServicesParams
}

type ListServicesResponseObject interface {
	VisitListServicesResponse(w http.ResponseWriter) error
}

type ListServices200JSONResponse ListServicesResponse

func (response ListServices200JSONResponse) VisitListServicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListServices400JSONResponse struct{ BadRequestJSONResponse }

func (response ListServices400JSONResponse) VisitListServicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListServices401JSONResponse struct{ UnAuthorizedJSONResponse }

func (response ListServices401JSONResponse) VisitListServicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListServices403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListServices403JSONResponse) VisitListServicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListServices429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response ListServices429JSONResponse) VisitListServicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type ListServices5XXJSONResponse struct {
	Body struct {
		Message *string `json:"message,omitempty"`
	}
	StatusCode int
}

func (response ListServices5XXJSONResponse) VisitListServicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateServiceRequestObject struct {
	Body *CreateServiceJSONRequestBody
}

type CreateServiceResponseObject interface {
	VisitCreateServiceResponse(w http.ResponseWriter) error
}

type CreateService200JSONResponse CreateServiceResponse

func (response CreateService200JSONResponse) VisitCreateServiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateService400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateService400JSONResponse) VisitCreateServiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateService401JSONResponse struct{ UnAuthorizedJSONResponse }

func (response CreateService401JSONResponse) VisitCreateServiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateService403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateService403JSONResponse) VisitCreateServiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateService409JSONResponse struct{ ConflictJSONResponse }

func (response CreateService409JSONResponse) VisitCreateServiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateService429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response CreateService429JSONResponse) VisitCreateServiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type CreateService5XXJSONResponse struct {
	Body struct {
		Message *string `json:"message,omitempty"`
	}
	StatusCode int
}

func (response CreateService5XXJSONResponse) VisitCreateServiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetServiceRequestObject struct {
	Name Name `json:"name"`
}

type GetServiceResponseObject interface {
	VisitGetServiceResponse(w http.ResponseWriter) error
}

type GetService200JSONResponse GetServiceResponse

func (response GetService200JSONResponse) VisitGetServiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetService401JSONResponse struct{ UnAuthorizedJSONResponse }

func (response GetService401JSONResponse) VisitGetServiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetService403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetService403JSONResponse) VisitGetServiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetService404JSONResponse struct{ NotFoundJSONResponse }

func (response GetService404JSONResponse) VisitGetServiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetService429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response GetService429JSONResponse) VisitGetServiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type GetService5XXJSONResponse struct {
	Body struct {
		Message *string `json:"message,omitempty"`
	}
	StatusCode int
}

func (response GetService5XXJSONResponse) VisitGetServiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /services)
	ListServices(ctx context.Context, request ListServicesRequestObject) (ListServicesResponseObject, error)

	// (POST /services)
	CreateService(ctx context.Context, request CreateServiceRequestObject) (CreateServiceResponseObject, error)

	// (GET /services/{name})
	GetService(ctx context.Context, request GetServiceRequestObject) (GetServiceResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListServices operation middleware
func (sh *strictHandler) ListServices(ctx *gin.Context, params ListServicesParams) {
	var request ListServicesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListServices(ctx, request.(ListServicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListServices")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListServicesResponseObject); ok {
		if err := validResponse.VisitListServicesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateService operation middleware
func (sh *strictHandler) CreateService(ctx *gin.Context) {
	var request CreateServiceRequestObject

	var body CreateServiceJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateService(ctx, request.(CreateServiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateService")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateServiceResponseObject); ok {
		if err := validResponse.VisitCreateServiceResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetService operation middleware
func (sh *strictHandler) GetService(ctx *gin.Context, name Name) {
	var request GetServiceRequestObject

	request.Name = name

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetService(ctx, request.(GetServiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetService")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetServiceResponseObject); ok {
		if err := validResponse.VisitGetServiceResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZbW/bNhD+KwTXb2NsJ+0GzJ+WJm1mLEmNph0KtFlBS2ebrUSqJJXGC/TfB5J6s0RL",
	"ctouy6fE8L08vHt4dzzf4UDEieDAtcLTO5xQSWPQIO2nC3r7GlQaue9CUIFkiWaC46n5DvE0XoBEYomk",
	"E0NaIAk6lRx9XQNHCV0xTjXjK0wwM2pfUpAbTDCnMeApjuntx1wXE6yCNcTU+VrSNNJ4ejiZECPF4jQu",
	"PjGefyJYbxJjhnENK5A4ywi+tJbvnLuE6nXlzf4hWMKXlEkI8VTLFOpun0hY4in+aVxFZey+VWNr1zqA",
	"W/1GfAY+40mq25GZ54cWHGkjtuPoHG71x0KggpCfSGlpopYZhxJUIrgCm4XnNHwNX1JQ1nMguAZu/6VJ",
	"ErHA+h1/UgbJXc1sIkUCUjNnJAal6Ap8/sqYisUnCLRDsH3A5zREMseQEXwi+DJiwcPheQ1KpDIAFBRI",
	"MoJfCrlgYQj8wWBVCDKCZ1yD5DS6AnkD8oWUQj4YsAILcmCQQ2OYLfRLkfLw4TPJhUZLCyUj+I0QF5Rv",
	"ctqrB0PXxJER/JYfp3otJPsHHi5ql0KjGgwjkBctWzAk5cG6qIoN8wSfSKAaDBNYALXKQsOQGfs0mteg",
	"LmmkgDTQK6fcV0BzH65qurpW1OH3pY3r1nlbEF0x/KEY94J3KoLPIE+MMQVz03A8LUGvTW8MrehB4GTR",
	"kkWAGEeFddJOjzNuBLstV3JDrL7gN93mRsBvBhr6i7phoRWXM9D/25ydMW3aFlulkrqj32HB4dUST993",
	"e2tqvrKhUzgb4qYQ3i8Oi60b3AWudtdNEVDrtzLqDd/VH0aqFT2nTOrefUecnbZZVJbx2Sk6QG/PZ6fY",
	"DnHnwFeGdUe/2imu/rHFrHOmCvqoe/KHF4Na72hXCpqo5U4H0k7t4p3yhutyftEi3j5HSuLewzQ8nKyF",
	"F6YxNQRhoT/4hlzOL8orSXpFz9lCUrnx35/a9/vFKaq0hvnfTkozVoW5boytxPpkr6qi9v1LYWW/+zxd",
	"pXGXjf0Ah76m2AW93UXNnNPqfv0mSumMYKj6XJdi0Q6dRtHQejSsWDOwhcMWdOKJSOXNm4e83m+X1jw1",
	"6NI9ZVtl87Je83rfpS31Vwnw4/nsWzIvEuA0YX0R9HnaVaoKk74wddnZD/hKnEQsH94HID/LxZ1nnA/q",
	"LuB7GXrTUKsMbmgcvWSRhwbHCyWiVANK8oEtDxEKYcm4PbGZ3IwBtBQyprqd7UaQS2cdUW6cufWO4V7O",
	"Gq4isUQrgQKrPuoFw3eNG90x2xNQZaUAhor7ZeMIIVKBSAB9ZVGEFoBoGEL4DejzWcsu2rR5hOMp/nvF",
	"9O+jnz98GK2YfuK7lPdrGUHzDg8YZhpdg+AV62Vxa5TOCGZhn9bs1MjxATNtuXerR5iFxSLNYSSN43qD",
	"v6OrDZ5qmsfcv8D5p5yth/HjSfK9k3e/vNnzMg2xGvwgLI1RKenGLUYgSCXTmysj62wez2d/wqZcGa+B",
	"hiCrPe27g+OEHRiJylzCzGe7imF8Keysx7Qp1PgUkkhsYuC6rCUXIgTzkroBqVwBmowORxODr2yW+Olo",
	"MjrCxG6sLaxx/SGyAp33VheoWYinW08kq1nt7neQuRIZ13b7u5hck27svA2Nt7bSR5PJXuuvrvR5X36e",
	"tZeRK2NcCRL8zIHx+ShBj2t7dKty2K+yteyzSk/7lba2wM+OfuvX8KwZf3n3rl/Pt2KuU96yoiD7+2tb",
	"iujKkKW6YtcZwYlQHrJtLeHyH1FA6eci3Hy3zHt3kVn7N5DvyTb/ctFDNyf42Ag3GUC4k9rPJo+AoRmp",
	"auP4zlTpbGeJrHaQexdI17p+ZKHzLEg9vDuDXVXuP2LQs36N8oejR8KgfM1XMCE1Mzke3xzi7Dr7NwAA",
	"//+eFT1nEx8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
