// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	APIKeyScopes = "APIKey.Scopes"
)

// BranchName defines model for BranchName.
type BranchName = string

// CreateServiceRequest defines model for CreateServiceRequest.
type CreateServiceRequest struct {
	Service ServiceInput `json:"service"`
}

// CreateServiceResponse defines model for CreateServiceResponse.
type CreateServiceResponse struct {
	Service Service `json:"service"`
}

// DockerComposePath Path to docker-compose file in service
type DockerComposePath = string

// DockerfilePath Path to Dockerfile file in service
type DockerfilePath = string

// EnvPath Path to .env file in service
type EnvPath = string

// EnvVars defines model for EnvVars.
type EnvVars = map[string]interface{}

// GetServiceResponse defines model for GetServiceResponse.
type GetServiceResponse struct {
	Service Service `json:"service"`
}

// GitConfiguration defines model for GitConfiguration.
type GitConfiguration struct {
	union json.RawMessage
}

// GitConfigurationOptions defines model for GitConfigurationOptions.
type GitConfigurationOptions struct {
	BranchName BranchName `json:"branchName"`
	SshUrl     SSHUrl     `json:"sshUrl"`
}

// ID Resource ID - ULID
type ID = string

// ListServicesResponse defines model for ListServicesResponse.
type ListServicesResponse struct {
	// NextToken Pagination token
	NextToken *NextToken `json:"nextToken,omitempty"`
	Services  Services   `json:"services"`
}

// NPMConfiguration defines model for NPMConfiguration.
type NPMConfiguration struct {
	Npm NPMConfigurationChoices `json:"npm"`
}

// NPMConfigurationChoices defines model for NPMConfigurationChoices.
type NPMConfigurationChoices struct {
	union json.RawMessage
}

// NPMLibrary defines model for NPMLibrary.
type NPMLibrary struct {
	Library NPMLibraryConfiguration `json:"library"`
}

// NPMLibraryConfiguration defines model for NPMLibraryConfiguration.
type NPMLibraryConfiguration = map[string]interface{}

// NPMService defines model for NPMService.
type NPMService struct {
	Service NPMServiceConfiguration `json:"service"`
}

// NPMServiceConfiguration defines model for NPMServiceConfiguration.
type NPMServiceConfiguration struct {
	// DockerComposePath Path to docker-compose file in service
	DockerComposePath DockerComposePath `json:"dockerComposePath"`

	// DockerfilePath Path to Dockerfile file in service
	DockerfilePath DockerfilePath `json:"dockerfilePath"`

	// EnvPath Path to .env file in service
	EnvPath EnvPath `json:"envPath"`
	EnvVars EnvVars `json:"envVars"`
}

// Name Service Name
type Name = string

// NextToken Pagination token
type NextToken struct {
	NextToken *string `json:"nextToken,omitempty"`
}

// OpenAPIConfiguration defines model for OpenAPIConfiguration.
type OpenAPIConfiguration struct {
	Openapi OpenAPIConfigurationChoices `json:"openapi"`
}

// OpenAPIConfigurationChoices defines model for OpenAPIConfigurationChoices.
type OpenAPIConfigurationChoices struct {
	TypescriptClient *OpenAPITypescriptClientConfig `json:"typescriptClient,omitempty"`

	// YamlFile Absolute path to openapi definition in yaml format
	YamlFile string `json:"yamlFile"`
}

// OpenAPITypescriptClientConfig defines model for OpenAPITypescriptClientConfig.
type OpenAPITypescriptClientConfig struct {
	// Name Name of typescript client. Service defined scope will be added.
	Name string `json:"name"`
}

// SSHUrl defines model for SSHUrl.
type SSHUrl = string

// Service defines model for Service.
type Service struct {
	Configuration ServiceConfiguration `json:"configuration"`
	Git           GitConfiguration     `json:"git"`

	// Id Resource ID - ULID
	Id ID `json:"id"`

	// Name Service Name
	Name Name `json:"name"`
}

// ServiceConfiguration defines model for ServiceConfiguration.
type ServiceConfiguration struct {
	union json.RawMessage
}

// ServiceInput defines model for ServiceInput.
type ServiceInput struct {
	Configuration ServiceConfiguration `json:"configuration"`
	Git           GitConfiguration     `json:"git"`

	// Name Service Name
	Name Name `json:"name"`
}

// Services defines model for Services.
type Services = []Service

// Version defines model for Version.
type Version = string

// MaxResults defines model for MaxResults.
type MaxResults = int

// NextTokenInput defines model for NextTokenInput.
type NextTokenInput = string

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Message *string `json:"message,omitempty"`
}

// Conflict defines model for Conflict.
type Conflict struct {
	Message *string `json:"message,omitempty"`
}

// Forbidden defines model for Forbidden.
type Forbidden struct {
	Message *string `json:"message,omitempty"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	Message *string `json:"message,omitempty"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Message *string `json:"message,omitempty"`
}

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests struct {
	Message *string `json:"message,omitempty"`
}

// UnAuthorized defines model for UnAuthorized.
type UnAuthorized struct {
	Message *string `json:"message,omitempty"`
}

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	// MaxResults Max number of results to return when paginating
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// NextToken Pagination token
	NextToken *NextTokenInput `form:"next_token,omitempty" json:"next_token,omitempty"`
}

// CreateServiceJSONRequestBody defines body for CreateService for application/json ContentType.
type CreateServiceJSONRequestBody = CreateServiceRequest

// AsGitConfigurationOptions returns the union data inside the GitConfiguration as a GitConfigurationOptions
func (t GitConfiguration) AsGitConfigurationOptions() (GitConfigurationOptions, error) {
	var body GitConfigurationOptions
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGitConfigurationOptions overwrites any union data inside the GitConfiguration as the provided GitConfigurationOptions
func (t *GitConfiguration) FromGitConfigurationOptions(v GitConfigurationOptions) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGitConfigurationOptions performs a merge with any union data inside the GitConfiguration, using the provided GitConfigurationOptions
func (t *GitConfiguration) MergeGitConfigurationOptions(v GitConfigurationOptions) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t GitConfiguration) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GitConfiguration) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsNPMService returns the union data inside the NPMConfigurationChoices as a NPMService
func (t NPMConfigurationChoices) AsNPMService() (NPMService, error) {
	var body NPMService
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNPMService overwrites any union data inside the NPMConfigurationChoices as the provided NPMService
func (t *NPMConfigurationChoices) FromNPMService(v NPMService) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNPMService performs a merge with any union data inside the NPMConfigurationChoices, using the provided NPMService
func (t *NPMConfigurationChoices) MergeNPMService(v NPMService) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNPMLibrary returns the union data inside the NPMConfigurationChoices as a NPMLibrary
func (t NPMConfigurationChoices) AsNPMLibrary() (NPMLibrary, error) {
	var body NPMLibrary
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNPMLibrary overwrites any union data inside the NPMConfigurationChoices as the provided NPMLibrary
func (t *NPMConfigurationChoices) FromNPMLibrary(v NPMLibrary) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNPMLibrary performs a merge with any union data inside the NPMConfigurationChoices, using the provided NPMLibrary
func (t *NPMConfigurationChoices) MergeNPMLibrary(v NPMLibrary) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NPMConfigurationChoices) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NPMConfigurationChoices) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsNPMConfiguration returns the union data inside the ServiceConfiguration as a NPMConfiguration
func (t ServiceConfiguration) AsNPMConfiguration() (NPMConfiguration, error) {
	var body NPMConfiguration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNPMConfiguration overwrites any union data inside the ServiceConfiguration as the provided NPMConfiguration
func (t *ServiceConfiguration) FromNPMConfiguration(v NPMConfiguration) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNPMConfiguration performs a merge with any union data inside the ServiceConfiguration, using the provided NPMConfiguration
func (t *ServiceConfiguration) MergeNPMConfiguration(v NPMConfiguration) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOpenAPIConfiguration returns the union data inside the ServiceConfiguration as a OpenAPIConfiguration
func (t ServiceConfiguration) AsOpenAPIConfiguration() (OpenAPIConfiguration, error) {
	var body OpenAPIConfiguration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOpenAPIConfiguration overwrites any union data inside the ServiceConfiguration as the provided OpenAPIConfiguration
func (t *ServiceConfiguration) FromOpenAPIConfiguration(v OpenAPIConfiguration) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOpenAPIConfiguration performs a merge with any union data inside the ServiceConfiguration, using the provided OpenAPIConfiguration
func (t *ServiceConfiguration) MergeOpenAPIConfiguration(v OpenAPIConfiguration) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ServiceConfiguration) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ServiceConfiguration) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZbW/bthP/KgT/ffdnbCftBsyvliZtZyxJjSQtCrRZQUtnm61EqiSVxgv03QeSerJE",
	"WXLWLu2rRPA9/O6Bd8fjPQ5EnAgOXCs8vcdroCFI+++La7oyf0NQgWSJZoLjKb5eA7oFqZjgSCyRXgOS",
	"oEQqA0AbkSIJX1JQGkJMsArWEFMj44mEJZ7i/40rbWP3qxq/ddJwlmUEJ1TSGHQO4ZzeXYJKI4dtG8g5",
	"vUM8jRcgDQ7pyJAWSIJOJUdf18BRQleMU834ChPMDNuXFOQGE8xpDHiKY3r3MefdAhzCkqaRxtPDyYQY",
	"KhancfHFeP5FsN4kRgzjGlYgsTHhwkq+d+oSqteVNvuHYOMjJiHEUy1TGOonK9cqgDt9LT4Dn/Ek1W3P",
	"zHOjBUfakHWYzuFOfywIKgi5RUpL4zUbFAkqEVyBjcJzGl66GJuvQHAN3P5LkyRigdU7/qQMkvua2ESK",
	"BKRmTkgMStEV+PSVPhWLTxBoh2DbwOc0LPIMZwSfCL6MWPB4eC6LAxAUSAwqCVTDFchbFsBl7sG9IO5K",
	"Br90DzZHiHJKVJIS31H3aczJxpbGKngp5IKFIfBHc3iFICP4Fejv5WWPaA+aV6C/qX9nXIPkNDIyQb6Q",
	"UshH83SBBTkwyKHJCD5jqvCN+uZ+9wr3oDN0bdebEin0S5Hy8PFLAhcaLS2UjOBrIc4p3+T1Uz0auiaO",
	"jOA3/DjVayHZ3/B4XrsQGtVgGII8JWznkZQH66K9NsS3Cm7ZomgYMiOfRvMa1CWNFJAGeuWY+9Iz1+Ha",
	"r2uQRUN/X8q4adm7oyd8N4x7wTsVwWeQJ0aYgrmZXDyzhV6bISu0pAeBo0VLFgFiHBXSSTs8Trgh3C25",
	"ohsi9QW/3S1uBPx2oKC31FXrll/8HebHiNkrps38w1appM70eyw4vF7i6fue5tbgfG1dp3A2RE1BvJ8f",
	"FlsneBe42lk3RUCt38io131XfxiqlvccM6lr95k4O21nUVnGZ6foAL05m51iexs4A74yWXf0q70O1D9b",
	"mdXVKffwGy8m/t47QklovJYrHZh2qivvlNddF/PzVuLtY1IS9xrT0HCyFl6YRtQQhAX/4BNyMT8vjyTp",
	"JT1jC0nlxn9+ar/v56eo4hqmfzsoTV8V4nZjbAXWR3tVFbVvXwor+bvt2VUau2TsBzj0NcVd0Ntd1Mw5",
	"re7XL6KkzgiGqs/tYizaoeMoGloPhyVrOrZQ2IJOPB6ptHnjkNf77dJajO0XbifSKpsX9ZrXu+DYUS97",
	"51CCXyfAj+ezf5MmIgFOE9bnbp+mrrpWiLwZiLhW3/YAbkQ7555ELJ/4B1hw3WBzSAy0DY2jlyzyhPx4",
	"oUSUakBJPpzlFqIQloxbwGZKMwLQUsiY6nZiNHxUKtvhpA6orbsL9+apyU+76SyloMCKGZU3TwsfQqQC",
	"kQD6yqIILQDRMIRw1GsB75pH8nHGwKTa3MLxFP+1Yvr30f8/fBitmH7iOzYPq8pBM/MHzAuNwkzwivUm",
	"T2tazQhmYR/X7NTQ8QFjY7kjrXuYhcXS02EkDXO9zu9oHIMHh6aZ+5cF/yCxdff8eYL84OA9LG7WXqYh",
	"VoPvXKUwKiXdmO/iYcLbQxQEqWR6c2XkOH3H89mfsClX/26xV+3b3x0cJ+zAUFSqEma+7SaE8aWwqpg2",
	"tROfQhKJTQy82nCdixDMRea2AIYno8PRxGAt2w9+OpqMjkxHpHptYY3r94AV6LxbOSfOwnyNVjpu+w2m",
	"I9ErknHtjaYry2vUjbcLk+JbrwtHk0lXxEq6jvUgwc+GMNfeLyzLYT/L1m7MMj3tZ9raUT87+q2fw7OV",
	"++Xdu34+3764nqI2ikVyvr+xZYWuTHCr43KTEZwI5UmOrZ1V/ngFSj8X4eZ7vWbk0Wm/PQ3Kjo6nkR86",
	"PSYD0uOk9rj0E+RTRqrKM743NTDrLEDVgm3v8uOaxoPKiO915z8M+bN+jvIZ4ycJeb50KkKXmvEVj28P",
	"cXaT/RMAAP//lNtcGWogAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
